{"timestamp":1729618875811,"message":"Unable to read hathifile url badURL","log.level":"ERROR","logger.name":"processes.ingest.hathi_trust","thread.id":140592270920576,"thread.name":"MainThread","process.id":2266,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/ingest/hathi_trust.py","line.number":93,"entity.type":"SERVICE"}
