{"timestamp":1665156164201,"message":"Unable to read hathifile url badURL","log.level":"ERROR","logger.name":"processes.hathiTrust","thread.id":139653317257024,"thread.name":"MainThread","process.id":2476,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/hathiTrust.py","line.number":94,"entity.type":"SERVICE"}
