{"timestamp":1730137725159,"message":"Unable to parse OCLC catalog record with id <MagicMock name='CatalogMapping().record.source_id' id='139680794024208'> due to ","log.level":"ERROR","logger.name":"processes.frbr.catalog","thread.id":139681453058944,"thread.name":"MainThread","process.id":2465,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/frbr/catalog.py","line.number":92,"entity.type":"SERVICE"}
