{"timestamp":1729011304313,"message":"Unable to cluster <MagicMock id='140118502449888'>","log.level":"ERROR","logger.name":"processes.sfrCluster","thread.id":140119168486272,"thread.name":"MainThread","process.id":2463,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/sfrCluster.py","line.number":106,"entity.type":"SERVICE"}
