{"timestamp":1724631827373,"message":"Database error","log.level":"ERROR","logger.name":"api.blueprints.drbUtils","thread.id":140116119038848,"thread.name":"MainThread","process.id":2399,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/api/blueprints/drbUtils.py","line.number":56,"entity.type":"SERVICE"}
