{"timestamp":1727978697890,"message":"Unable to get total counts","log.level":"ERROR","logger.name":"api.blueprints.drbUtils","thread.id":139705303374720,"thread.name":"MainThread","process.id":2329,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/api/blueprints/drbUtils.py","line.number":56,"entity.type":"SERVICE","error.class":"builtins:Exception","error.message":"Database error"}
