{"timestamp":1729691673306,"message":"Unable to load metadata files for work 1","log.level":"ERROR","logger.name":"managers.gutenberg","thread.id":139779400858496,"thread.name":"MainThread","process.id":2361,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/managers/gutenberg.py","line.number":91,"entity.type":"SERVICE"}
