ERROR    api.blueprints.drbLink:drbLink.py:36 Database error