{"timestamp":1727875314775,"message":"Unable to get link with id 1","log.level":"ERROR","logger.name":"api.blueprints.drbLink","thread.id":140333006801792,"thread.name":"MainThread","process.id":2326,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/api/blueprints/drbLink.py","line.number":36,"entity.type":"SERVICE","error.class":"builtins:Exception","error.message":"Database error"}
