{"timestamp":1730075268014,"message":"Unable to read Hathi Trust file row","log.level":"ERROR","logger.name":"processes.ingest.hathi_trust","thread.id":140234561973120,"thread.name":"MainThread","process.id":2383,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/ingest/hathi_trust.py","line.number":110,"entity.type":"SERVICE","error.class":"_csv:Error","error.message":""}
