{"timestamp":1729542773943,"message":"Unable to parse OCLC catalog record with id <MagicMock name='CatalogMapping().record.source_id' id='139872252358080'> due to ","log.level":"ERROR","logger.name":"processes.oclcCatalog","thread.id":139872921095040,"thread.name":"MainThread","process.id":2292,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/oclcCatalog.py","line.number":92,"entity.type":"SERVICE"}
