{"timestamp":1730405451302,"message":"Unable to read Hathi Trust file url badURL","log.level":"ERROR","logger.name":"processes.ingest.hathi_trust","thread.id":139849462053760,"thread.name":"MainThread","process.id":2344,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/ingest/hathi_trust.py","line.number":98,"entity.type":"SERVICE","error.class":"requests.exceptions:HTTPError","error.message":""}
